// Code generated by protoc-gen-go-enhance. DO NOT EDIT.

package structpb

import (
	proto "google.golang.org/protobuf/proto"
)

func (x *Struct) Clone() *Struct {
	return proto.Clone(x).(*Struct)
}
func (x *Value) Clone() *Value {
	return proto.Clone(x).(*Value)
}
func (x *ListValue) Clone() *ListValue {
	return proto.Clone(x).(*ListValue)
}
