// Code generated by protoc-gen-go-enhance. DO NOT EDIT.

package structpb

import (
	proto "google.golang.org/protobuf/proto"
)

func (x *Dict) Clone() *Dict {
	return proto.Clone(x).(*Dict)
}
func (x *Value) Clone() *Value {
	return proto.Clone(x).(*Value)
}
func (x *List) Clone() *List {
	return proto.Clone(x).(*List)
}
